### ISSUE TITLE
Move Image Builder to its own repo & create validation/gating

### ISSUE THREAD

**Issue by eak13** [airshipit/image-builder#1]
We need to move Image Builder from the Images repository into its own repo so it can have its own set of gating & validation put in place without impacting the build/gating on the Images repo. 

The following will need to occur:

1. Work with Airship project managers to get the Image Builder repo created in opendev & mirrored to github
2. Move current Image Builder code from Images to the new Image Builder repo and make any code updates to reflect the new location
3. Developing CI/gating to provide the ability to validate that the system configurations are being applied as expected by the images generated by Image Builder. This may include deploying a VM using a generated image & then validating various configuration settings like grub, system settings, CGroup driver, etc. 

This came from the 3/25 design call & the additional requirement to move its own repo came out of the 4/14 Flight Plan call. Validation will likely require further discussion on approach, tools to perform validation, etc.

**Comment by DannyMassa** [comment]
Relevant Patchsets: 
    

- https://review.opendev.org/c/airship/image-builder/+/796526
- https://review.opendev.org/c/airship/image-builder/+/800971

    
Validation can be done by cross referencing the commit hash associated with the newest PS and seeing that the commit hash is being published to quay:


- https://quay.io/repository/airshipit/qcow-bundle?tab=tags
- https://quay.io/repository/airshipit/image-builder?tab=tags

Closes #1

**Comment by eak13** [comment]
Closing out per patchset merges & above validation via quay.io.
